We have a baseline-like example scheduler in `rubin_sim`. Let's load that up and see what it looks like

In [1]:
import numpy as np
import healpy as hp
import matplotlib.pylab as plt
%matplotlib inline
import pandas as pd

from rubin_sim.scheduler import sim_runner
from rubin_sim.scheduler.model_observatory import ModelObservatory
from rubin_sim.scheduler.example import example_scheduler


In [2]:
mjd_start=60676.0
scheduler = example_scheduler(mjd_start=mjd_start)
scheduler

Optimizing ELAISS1
Optimizing XMM_LSS
Optimizing ECDFS
Optimizing COSMOS
Optimizing EDFS_a


CoreScheduler(
            surveys=[[<ScriptedSurvey survey_name='' at 0x295f333d0>, <ScriptedSurvey survey_name='' at 0x295f2cb50>], [<LongGapSurvey survey_name='Long Gap (Blob survey g_r + )' at 0x179a835d0>, <LongGapSurvey survey_name='Long Gap (Blob survey r_i + )' at 0x179a38450>, <LongGapSurvey survey_name='Long Gap (Blob survey i_z + )' at 0x179ab1cd0>], [<BlobSurvey survey_name='Blob survey u_g' at 0x17f5304d0>, <BlobSurvey survey_name='Blob survey u_r' at 0x17a9f42d0>, <BlobSurvey survey_name='Blob survey g_r' at 0x179fb8650>, <BlobSurvey survey_name='Blob survey r_i' at 0x179a35090>, <BlobSurvey survey_name='Blob survey i_z' at 0x179f03950>, <BlobSurvey survey_name='Blob survey z_y' at 0x179fbc410>, <BlobSurvey survey_name='Blob survey y_y' at 0x179f378d0>], [<BlobSurvey survey_name='Blob survey r_i' at 0x179ffbf10>, <BlobSurvey survey_name='Blob survey i_z' at 0x179a7ca90>, <BlobSurvey survey_name='Blob survey z_y' at 0x179a1bc50>, <BlobSurvey survey_name='Blob survey y_y' at 0x179fc70d0>], [<BlobSurvey survey_name='Blob survey r_r' at 0x179fc7910>, <BlobSurvey survey_name='Blob survey i_i' at 0x179b15950>, <BlobSurvey survey_name='Blob survey z_z' at 0x295ef8610>], [<GreedySurvey survey_name='greedy' at 0x179ad7890>, <GreedySurvey survey_name='greedy' at 0x179fd8250>, <GreedySurvey survey_name='greedy' at 0x179a6fd10>, <GreedySurvey survey_name='greedy' at 0x179ac4450>]],
            camera="LSST",
            nside=32,
            rotator_limits=array([1.48352986, 4.79965544]),
            survey_index=[None, None],
            log=<Logger CoreScheduler (WARNING)>
        )

There we can see the heirarchy of survey objects in the core scheduler. We have 

* 5 DDF surveys
* 3 LongGap surveys
* 7 blob surveys
* 4 blob surveys
* 3 blob surveys
* 1 greedy survey


In [ ]:
# let's try running it for a few days

mo = ModelObservatory(mjd_start=mjd_start)
mo, scheduler, observations = sim_runner(mo, scheduler, survey_length=10.0, verbose=True)

/Users/yoachim/git_repos/rubin_sim/rubin_sim/skybrightness_pre/sky_model_pre.py:272: UserWarning: Requested MJD between sunrise and sunset, returning closest maps
  warnings.warn(


> /Users/yoachim/git_repos/rubin_sim/rubin_sim/scheduler/model_observatory/kinem_model.py(462)slew_times()
    460         # And delta_az is signed properly.
    461         import pdb ; pdb.set_trace()
--> 462         stacked_az = np.vstack([delta_az_short, delta_az_long])
    463         indx = np.argmin(np.abs(stacked_az), axis=0)
    464         delta_aztel = np.take_along_axis(

ipdb> check = np.minimum(delta_az_short, delta_az_long)
ipdb> check
array([-7.93870789e-02, -4.12296179e-02, -2.93118589e-03, ...,
       -3.17110356e+00, -3.14078585e+00, -3.11205741e+00])
ipdb> stacked_az = np.vstack([delta_az_short, delta_az_long])
ipdb> indx = np.argmin(np.abs(stacked_az), axis=0)
ipdb> delta_aztel = np.take_along_axis(stacked_az, np.expand_dims(indx, axis=0), axis=0).squeeze(axis=0)
ipdb> delta_aztel
array([-7.93870789e-02, -4.12296179e-02, -2.93118589e-03, ...,
        3.11208174e+00, -3.14078585e+00, -3.11205741e+00])
ipdb> delta_aztel == check
array([ True,  True,  True, ..., False

In [4]:
# Let's see what kind of observations executed
np.unique(observations['note'])

array(['DD:COSMOS', 'DD:ECDFS', 'DD:EDFS_a', 'DD:EDFS_b', 'DD:ELAISS1',
       'DD:XMM_LSS', 'blob, iz, a', 'blob, iz, b', 'blob, ri, a',
       'blob, ri, b', 'blob, yy, a', 'blob, yy, b', 'blob, zy, a',
       'blob, zy, b', 'blob_long, iz, a', 'blob_long, iz, b',
       'blob_twi, iz, a', 'blob_twi, iz, b', 'blob_twi, ri, a',
       'blob_twi, ri, b', 'blob_twi, yy, a', 'blob_twi, yy, b',
       'blob_twi, zy, a', 'blob_twi, zy, b', 'greedy', 'long',
       'twilight_neo'], dtype='<U40')